### ISSUE TITLE
401 Authorization error from npm.fontawesome when doing a yarn build

### ISSUE THREAD

**Issue by xdls** [charliebeckstrand/recipes#1]
Saw an error when attempting to do an initial 'yarn build'. 

`error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-regular-svg-icons/-/free-regular-svg-icons-5.7.1.tgz: Request failed \"401 Unauthorized\"".
`

As per [this suggestion](https://github.com/FortAwesome/Font-Awesome/issues/12609#issuecomment-373287291), I changed urls in the yarn.lock file to https://registry.yarnpkg.com/ instead of npm.fontawesome.com and things started working. Will make a PR in a bit but wanted to open an issue to point it out.

**Comment by charliebeckstrand** [comment]
I forgot to add my FontAwesome npm Package Token. That's added now and this is fixed.
